
mkoctfile imageset_to_leveldb.cpp -lcaffe -lglog -lgflags -lprotobuf -lleveldb -llmdb ...
 -L/home/kazeka/src/deep-metric-learning/caffe/build/lib ...
 -I/home/kazeka/src/deep-metric-learning/caffe/build/src/caffe/proto

mkoctfile serialized_pairs_to_leveldb.cpp -lcaffe -lglog -lgflags -lprotobuf -lleveldb -llmdb ...
 -L/home/kazeka/src/deep-metric-learning/caffe/build/lib ...
 -I/home/kazeka/src/deep-metric-learning/caffe/build/src/caffe/proto
